 export const degreeSubjects = {
    '10': [
      'Mathematics', 
      'Science', 
      'Social Studies', 
      'Bengali', 
      'English', 
      'Hindi', 
      'History', 
      'Geography'
    ],
    '12': [
      'Physics', 
      'Chemistry', 
      'Biology', 
      'Mathematics', 
      'Bengali', 
      'English', 
      'Computer Science', 
      'Economics', 
      'Accountancy', 
      'Business Studies', 
      'Political Science', 
      'Sociology'
    ],
    'UG': [
      'Computer Science', 
      'Mechanical Engineering', 
      'Civil Engineering', 
      'Bengali Literature', 
      'Physics', 
      'Chemistry', 
      'Biology', 
      'Mathematics', 
      'Economics', 
      'Psychology', 
      'History', 
      'Geography', 
      'Political Science', 
      'Sociology', 
      'Law', 
      'Business Administration'
    ],
    'PG': [
      'Data Science', 
      'Robotics', 
      'AI & ML', 
      'Advanced Bengali Literature', 
      'Applied Physics', 
      'Organic Chemistry', 
      'Molecular Biology', 
      'Pure Mathematics', 
      'Econometrics', 
      'Clinical Psychology', 
      'Modern History', 
      'Urban Geography', 
      'International Relations', 
      'Advanced Sociology', 
      'Corporate Law', 
      'Business Management'
    ]
  };